### ISSUE TITLE
Using storage causes high server load 

### ISSUE THREAD

**Issue by Vijabei** [McJtyMods/RFToolsStorage#1]
Hello McJty,

great work porting and enhancing the RFTools. Much love from me (and some others I am hosting a server for).

Really unfortunately I experienced a bug within your really nice Alpha version. After accessing the Modular Storage the server got a high load and often disconnects due time out.

Hope the following output of the server console might help:

`[K[1;31m[21:19:15] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake
[m>....
[K[1;31m[21:21:08] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 74 on channel rftoolsbase:rftoolsbase
[m>....
[K[1;31m[21:21:09] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 74 on channel rftoolsbase:rftoolsbase
[m>....
[K[1;31m[21:21:39] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.IndexOutOfBoundsException: index: 10, length: 115 (expected: range(0, 50))
at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1362) ~[server-1.14.4-extra-stable.jar:?] {}
at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1357) ~[server-1.14.4-extra-stable.jar:?] {}
at io.netty.buffer.PooledUnsafeDirectByteBuf.nioBuffer(PooledUnsafeDirectByteBuf.java:324) ~[server-1.14.4-extra-stable.jar:?] {}
at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:769) ~[server-1.14.4-extra-stable.jar:?] {}
at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1222) ~[server-1.14.4-extra-stable.jar:?] {}
at net.minecraft.network.PacketBuffer.toString(PacketBuffer.java:1068) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:319) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at mcjty.lib.network.PacketServerCommandTyped.<init>(PacketServerCommandTyped.java:30) ~[?:1.14-3.5.12-alpha] {re:classloading}
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_171] {}
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?] {re:classloading}
at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?] {re:classloading}
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_171] {}
at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?] {re:classloading}
at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?] {re:classloading}
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] {}
[m>....
[K[32m[21:22:12] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: xyz lost connection: Timed out
[m>....`

For a logfile I need some more time, if still necessary. The last logs were a big mess and I have to wait until the next have some content.

Thank you.

Regards,
Vija

**Comment by McJty** [comment]
Last update should fix this. Let me know if it doesn't and show me the full server log in that case
