### ISSUE TITLE
client crash while using RFTools Storage scanner

### ISSUE THREAD

**Issue by natebc** [McJtyMods/RFToolsStorage#24]
crash-report: https://gist.github.com/natebc/49a3d12688b7e9263f226f1d98f1df74

Time: 2020-10-21 08:45:30 EDT
Description: Rendering screen

java.lang.NullPointerException
    at mcjty.lib.gui.widgets.Slider.mouseWheel(Slider.java:178)
    at mcjty.lib.gui.widgets.AbstractContainerWidget.mouseWheel(AbstractContainerWidget.java:46)
    at mcjty.lib.gui.widgets.AbstractContainerWidget.mouseWheel(AbstractContainerWidget.java:46)
    at mcjty.lib.gui.Window.draw(Window.java:292)
    at mcjty.lib.gui.WindowManager.lambda$draw$3(WindowManager.java:87)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
    at mcjty.lib.gui.WindowManager.draw(WindowManager.java:87)
    at mcjty.lib.gui.GenericGuiContainer.drawWindow(GenericGuiContainer.java:272)
    at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.drawWindow(GuiStorageScanner.java:640)
    at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.drawGuiContainerBackgroundLayer(GuiStorageScanner.java:593)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at mcjty.lib.gui.GenericGuiContainer.drawScreen(GenericGuiContainer.java:277)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)

also reported to modpack: FTBTeam/FTB-University/issues/37

**Comment by McJty** [comment]
Versions please?

**Comment by natebc** [comment]
The crash report lists:
>        | LCHIJA | rftools                           | 7.73                     | rftools-1.12-7.73.jar                               | None                                     
That appears to still be the verson on the [modlist for the pack](https://www.feed-the-beast.com/modpack/ftb_university) as well.

**Comment by McJty** [comment]
This is weird. The storage scanner is used a lot on 1.12. I use it myself in my own letsplay and many others do too. Never had this reported before. I also no longer develop on 1.12 so there is not much that I can do about this I'm afraid

**Comment by natebc** [comment]
No worries at all @McJty I brought it here at the request of the FTB team on the pack issue tracker. I appreciate you taking the time to look it over.

Long live the beloved storage scanner!
