### ISSUE TITLE
Remote Storage Module make the game crash

### ISSUE THREAD

**Issue by draymone** [McJtyMods/RFToolsStorage#70]
Hello, when i place a Remote Storage Module in a Modular Storage my game crash instantly, the crash report is below.
I've RFTools Base 3.0.11 and RFTools Storage 3.0.9 in minecraft 1.18.2

`java.lang.NegativeArraySizeException: -1
	at net.minecraft.core.NonNullList.m_122780_(NonNullList.java:25) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,re:classloading}
	at mcjty.rftoolsstorage.storage.StorageEntry.<init>(StorageEntry.java:45) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at mcjty.rftoolsstorage.storage.StorageHolder.getOrCreateStorageEntry(StorageHolder.java:39) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at mcjty.rftoolsstorage.storage.GlobalStorageItemWrapper.createStorage(GlobalStorageItemWrapper.java:46) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at mcjty.rftoolsstorage.storage.GlobalStorageItemWrapper.getStacks(GlobalStorageItemWrapper.java:53) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at mcjty.rftoolsstorage.storage.GlobalStorageItemWrapper.getStackInSlot(GlobalStorageItemWrapper.java:101) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at net.minecraftforge.items.SlotItemHandler.m_7993_(SlotItemHandler.java:40) ~[forge-1.18.2-40.1.68-universal.jar%23173!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:168) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:A}
	at mcjty.lib.container.GenericContainer.m_38946_(GenericContainer.java:480) ~[mcjtylib-1.18-6.0.16.jar%23119!/:1.18-6.0.16] {re:classloading}
	at mcjty.rftoolsstorage.modules.modularstorage.blocks.ModularStorageContainer.m_38946_(ModularStorageContainer.java:173) ~[rftoolsstorage-1.18-3.0.9.jar%23141!/:1.18-3.0.9] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerPlayer,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}`

**Comment by McJty** [comment]
Remote storage is not implemented. There is a reason there is no recipe for it
